CC = gcc
CFLAGS = -Wall
SRC = src
INCLUDE = headers
OBJ = obj
EXECUTABLE = bmpl.exe

SRCS = $(wildcard $(SRC)/*.c)
OBJS = $(patsubst $(SRC)/%.c, $(OBJ)/%.o,$(SRCS))

.PHONY: all clean

all: $(EXECUTABLE)

$(EXECUTABLE): $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $@

$(OBJ)/%.o: $(SRC)/%.c | $(OBJ)
	$(CC) $(CFLAGS) -I$(INCLUDE) -c $< -D__USE_MINGW_ANSI_STDIO -o $@

$(OBJ):
	mkdir $@

clean:
	del /Q $(OBJ)\* 2>nul
	del $(EXECUTABLE) 2>nul
	rmdir $(OBJ) 2>nul