CC = gcc
CFLAGS = -Wall
INCLUDE = include
EXECUTABLE = bmpl
SRC = src
OBJ = obj
SRCS = $(wildcard $(SRC)/*.c)
OBJS = $(patsubst $(SRC)/%.c, $(OBJ)/%.o, $(SRCS))
all: $(EXECUTABLE)

$(EXECUTABLE): $(OBJS) $(OBJ)
	$(CC) $(CFLAGS) $(OBJS) -o $@ -I $(INCLUDE)

$(OBJ)/%.o: $(SRC)/%.c $(OBJ)
	$(CC) $(CFLAGS) -c $< -o $@

$(OBJ):
	mkdir -p $@